### PR TITLE
Update script.js

### PR DESCRIPTION
**Pull request by Abrarlala**

### CODE REVIEW

**Comment by theravi04** [comment]
@Abrarlala you have added the below code why, explain its use.
userInput.addEventListener("click" , ()=>{
    userInput.value =""
})

**Comment by theravi04** [comment]
@Abrarlala add the type of feature added in the description of your PR

**Comment by Abrarlala** [comment]
Becouse when we enter the city double by clicking on userinput the previous
one entry stay there so now when we click on userinput the previous entry
will be disappear

**Comment by Abrarlala** [comment]
> @Abrarlala add the type of feature added in the description of your PR
add a new feature , when we enter the city double by clicking on userinput the previous
one entry stay there so now when we click on userinput the previous entry
will be disappear.

**Pull request merged**
